# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d7b6c11ddffa1bf6355b64e437b5364e726c4ff91e94763ba02b47194f4f3b0490c7bcf2643bdd685f71f01a287856a28fc8d026e8e2f2c22c47192cb5a1c2

test:
  secret_key_base: 245d58b0b457079228482e2f3cc81b564b8bdf5db54101808e1f4a3d09585deda8e84182d1d1dd864819040365c97dbb93b91f13d8b8188a6ec82110ca6c35c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
